use_frameworks!

target 'TheKeyOAuthSwift_Example' do
  pod 'TheKeyOAuthSwift', :path => '../'
  pod 'GTMAppAuth'
  
  target 'TheKeyOAuthSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
